{{- if .Values.deployment }}
{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "application.labels.http-echo" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- end }}
{{- if or .Values.deployment.annotations .Values.deployment.reloadOnChange }}
  annotations:
{{- end }}
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
{{- if .Values.deployment.reloadOnChange }} 
    reloader.http-echo.com/auto: "true"
{{- end }}
  name: {{ template "application.name" . }}
  namespace: {{ template "application.namespace" . }}
spec:
{{- if .Values.deployment.replicas }}
  replicas: {{ .Values.deployment.replicas }}
{{- end }}
  selector:
    matchLabels:
{{ include "application.labels.selector" . | indent 6 }}
  {{- if .Values.deployment.strategy }}
  strategy:
{{ toYaml .Values.deployment.strategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
{{ include "application.labels.selector" . | indent 8 }}
    spec: 
      containers:
      - name: {{ template "application.name" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        {{- if .Values.deployment.args }}
        args: {{- include "application.tplvalues.render" (dict "value" .Values.deployment.args "context" $) | nindent 12 }}
        {{- end }}
        {{- if .Values.deployment.ports }}
        ports:
{{ toYaml .Values.deployment.ports | indent 10 }}
        {{- end }}
        {{- if .Values.deployment.startupProbe.enabled }}
        startupProbe:
          failureThreshold: {{ .Values.deployment.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment.startupProbe.periodSeconds }}
          successThreshold: {{ .Values.deployment.startupProbe.successThreshold }}
          timeoutSeconds: {{ .Values.deployment.startupProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.deployment.startupProbe.initialDelaySeconds }}
          {{- if .Values.deployment.startupProbe.exec }}
          exec:
            {{- toYaml .Values.deployment.startupProbe.exec | nindent 12 }}
          {{- else if .Values.deployment.startupProbe.httpGet }}
          httpGet:
            {{- toYaml .Values.deployment.startupProbe.httpGet | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.deployment.livenessProbe.enabled }} 
        livenessProbe:
          failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.deployment.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          {{- if .Values.deployment.livenessProbe.exec }}
          exec:
            {{- toYaml .Values.deployment.livenessProbe.exec | nindent 12 }}
          {{- else if .Values.deployment.livenessProbe.httpGet }}
          httpGet:
            {{- toYaml .Values.deployment.livenessProbe.httpGet | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe.enabled }} 
        readinessProbe:
          failureThreshold: {{ .Values.deployment.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.deployment.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.deployment.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          {{- if .Values.deployment.readinessProbe.exec }}
          exec:
            {{- toYaml .Values.deployment.readinessProbe.exec | nindent 12 }}
          {{- else if .Values.deployment.readinessProbe.httpGet }}
          httpGet:
            {{- toYaml .Values.deployment.readinessProbe.httpGet | nindent 12 }}
          {{- end }}
        resources:
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
            cpu: {{ .Values.deployment.resources.limits.cpu }}
          requests:
            memory: {{ .Values.deployment.resources.requests.memory }}
            cpu: {{ .Values.deployment.resources.requests.cpu }}
        {{- end }}
{{- end }}